/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 07-jul.-2025 22:01:20 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

CREATE DATABASE DDL_MOANSO
GO

USE DDL_MOANSO
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Bebida_Tipobebida]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Bebida] DROP CONSTRAINT [FK_Bebida_Tipobebida]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Comprainsumos_Proveedor]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Comprainsumos] DROP CONSTRAINT [FK_Comprainsumos_Proveedor]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Comprainsumos_RequerimientoDeInsumo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Comprainsumos] DROP CONSTRAINT [FK_Comprainsumos_RequerimientoDeInsumo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ComprobanteDeVenta_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ComprobanteDeVenta] DROP CONSTRAINT [FK_ComprobanteDeVenta_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ComprobanteDeVenta_Ordenpedido]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ComprobanteDeVenta] DROP CONSTRAINT [FK_ComprobanteDeVenta_Ordenpedido]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Detallepedido_Platillo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Detallepedido] DROP CONSTRAINT [FK_Detallepedido_Platillo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Detallepedido_Ordenpedido]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Detallepedido] DROP CONSTRAINT [FK_Detallepedido_Ordenpedido]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Detallesreq_RequerimientoDeInsumo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Detallesreq] DROP CONSTRAINT [FK_Detallesreq_RequerimientoDeInsumo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Detallesreq_Insumos]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Detallesreq] DROP CONSTRAINT [FK_Detallesreq_Insumos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Ordenpedido_Mesero]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Ordenpedido] DROP CONSTRAINT [FK_Ordenpedido_Mesero]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Platillo_Tipoplatillo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Platillo] DROP CONSTRAINT [FK_Platillo_Tipoplatillo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_RequerimientoDeInsumo_Encargadoalmacen]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [RequerimientoDeInsumo] DROP CONSTRAINT [FK_RequerimientoDeInsumo_Encargadoalmacen]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Bebida]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Bebida]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Comprainsumos]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Comprainsumos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ComprobanteDeVenta]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ComprobanteDeVenta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Detallepedido]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Detallepedido]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Detallesreq]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Detallesreq]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Encargadoalmacen]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Encargadoalmacen]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Insumos]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Insumos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Mesero]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Mesero]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Ordenpedido]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Ordenpedido]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Platillo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Platillo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Proveedor]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Proveedor]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[RequerimientoDeInsumo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [RequerimientoDeInsumo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tipobebida]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tipobebida]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tipoplatillo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tipoplatillo]
GO

/* Create Tables */

CREATE TABLE [Bebida]
(
	[Nombre_Bebida] varchar(50) NULL,
	[BebidaID] int NOT NULL,
	[TipobebidaID] int NOT NULL,
	[Precio] decimal(10,2) NULL,
	[TamañoBebida] varchar(20) NULL,
	[EstadoBebida] bit NULL
)
GO

CREATE TABLE [Cliente]
(
	[ClienteID] int NOT NULL,
	[Nombre_Cliente] varchar(50) NULL,
	[DNI] int NULL,
	[Numero] int NULL,
	[Correo] varchar(50) NULL,
	[Fecha] datetime2(7) NULL,
	[EstadoCliente] bit NULL
)
GO

CREATE TABLE [Comprainsumos]
(
	[ComprainsumosID] int NOT NULL,
	[RequerimientoDeInsumoID] int NULL,
	[EstadoCompra] bit NULL,
	[Encargado] varchar(50) NULL,
	[FechaCompra] datetime2(7) NULL,
	[MetodoPago] varchar(50) NULL,
	[MontoTotal] decimal(10,2) NULL,
	[ProveedorID] int NULL
)
GO
SELECT * FROM Comprainsumos;


CREATE TABLE [ComprobanteDeVenta]
(
	[ComprobanteDeVentaID] int NOT NULL,
	[ClienteID] int NULL,
	[OrdenpedidoID] int NOT NULL,
	[PedidoID] int NULL,
	[TipoComprobante] varchar(50) NULL,
	[FechaEmision] datetime2(7) NULL,
	[MontoTotal] decimal(10,2) NULL,
	[EstadoComprobante] bit NULL
)
GO

CREATE TABLE [Detallepedido]
(
	[DetallepedidoID] int IDENTITY(1,1)NOT NULL,
	[OrdenpedidoID] int NULL,
	[Cantidad] int NULL,
	[Subtotal] decimal(10,2) NULL,
	[PlatilloID] int NULL
)
GO

CREATE TABLE [Detallesreq]
(
	[DetallesreqID] int IDENTITY(1,1)NOT NULL,
	[RequerimientoDeInsumoID] int NOT NULL,
	[Cantidad] Varchar(50) NULL,
	[InsumosID] int NULL
)
GO

CREATE TABLE [Encargadoalmacen]
(
	[EncargadoalmacenID] int NOT NULL,
	[DNI] int NULL,
	[Nombre] varchar(50) NULL,
	[Numero] varchar(9) NULL,
	[FechaRegistro] datetime2(7) NULL,
	[Estado] bit NULL
)
GO

CREATE TABLE [Insumos]
(
	[InsumosID] int NOT NULL,
	[Nombre] varchar(50) NULL,
	[Cantidad] varchar(50) NULL,
	[Estado] bit NULL
)
GO

CREATE TABLE [Mesero]
(
	[MeseroID] int NOT NULL,
	[Nombre_Mesero] varchar(100) NULL,
	[DNI_Mesero] int NULL,
	[Telefono] varchar(9) NULL,
	[FechaIngreso] datetime2(7) NULL,
	[EstadoMesero] bit NULL
)
GO

CREATE TABLE [Ordenpedido]
(
	[OrdenpedidoID] int NOT NULL,
	[Fecha] datetime2(7) NULL,
	[MeseroID] int NOT NULL,
	[Estado] bit NULL,
	[NroMesa] int NULL,
	[Total] decimal(18) NULL
)
GO

CREATE TABLE [Platillo]
(
	[PlatilloID] int NOT NULL,
	[NombrePlatillo] varchar(50) NULL,
	[TipoplatilloID] int NOT NULL,
	[Precio] decimal(10,2) NULL,
	[EstadoPlatillo] bit NULL
)
GO

CREATE TABLE [Proveedor]
(
	[ProveedorID] int NOT NULL,
	[NombreProveedor] varchar(50) NULL,
	[RUC] varchar(11) NULL,
	[EmailProveedor] varchar(50) NULL,
	[FechaProveedor] datetime2(7) NULL,
	[EstadoProveedor] bit NULL
)
GO

CREATE TABLE [RequerimientoDeInsumo]
(
	[RequerimientoDeInsumoID] int NOT NULL,
	[Estado] bit NULL,
	[FechaRegistro] datetime2(7) NULL,
	[IDEncargado] int NULL
)
GO


CREATE TABLE [Tipobebida]
(
	[IdTipoBebida] int NOT NULL,
	[NombreTipo] varchar(50) NULL,
	[Estado] bit NULL
)
GO

CREATE TABLE [Tipoplatillo]
(
	[IdTipoPlatillo] int NOT NULL,
	[NombreTipo] varchar(50) NULL,
	[Estado] bit NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Bebida] 
 ADD CONSTRAINT [PK_Bebida]
	PRIMARY KEY CLUSTERED ([BebidaID] ASC)
GO

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([ClienteID] ASC)
GO

ALTER TABLE [Comprainsumos] 
 ADD CONSTRAINT [PK_Comprainsumos]
	PRIMARY KEY CLUSTERED ([ComprainsumosID] ASC)
GO

ALTER TABLE [ComprobanteDeVenta] 
 ADD CONSTRAINT [PK_ComprobanteDeVenta]
	PRIMARY KEY CLUSTERED ([ComprobanteDeVentaID] ASC)
GO

ALTER TABLE [Detallepedido] 
 ADD CONSTRAINT [PK_Detallepedido]
	PRIMARY KEY CLUSTERED ([DetallepedidoID] ASC)
GO

ALTER TABLE [Detallesreq] 
 ADD CONSTRAINT [PK_Detallesreq]
	PRIMARY KEY CLUSTERED ([DetallesreqID] ASC)
GO

ALTER TABLE [Encargadoalmacen] 
 ADD CONSTRAINT [PK_Encargadoalmacen]
	PRIMARY KEY CLUSTERED ([EncargadoalmacenID] ASC)
GO

ALTER TABLE [Insumos] 
 ADD CONSTRAINT [PK_Insumos]
	PRIMARY KEY CLUSTERED ([InsumosID] ASC)
GO

ALTER TABLE [Mesero] 
 ADD CONSTRAINT [PK_Mesero]
	PRIMARY KEY CLUSTERED ([MeseroID] ASC)
GO

ALTER TABLE [Ordenpedido] 
 ADD CONSTRAINT [PK_Ordenpedido]
	PRIMARY KEY CLUSTERED ([OrdenpedidoID] ASC)
GO

ALTER TABLE [Platillo] 
 ADD CONSTRAINT [PK_Platillo]
	PRIMARY KEY CLUSTERED ([PlatilloID] ASC)
GO

ALTER TABLE [Proveedor] 
 ADD CONSTRAINT [PK_Proveedor]
	PRIMARY KEY CLUSTERED ([ProveedorID] ASC)
GO

ALTER TABLE [RequerimientoDeInsumo] 
 ADD CONSTRAINT [PK_RequerimientoDeInsumo]
	PRIMARY KEY CLUSTERED ([RequerimientoDeInsumoID] ASC)
GO

ALTER TABLE [Tipobebida] 
 ADD CONSTRAINT [PK_Tipobebida]
	PRIMARY KEY CLUSTERED ([IdTipoBebida] ASC)
GO

ALTER TABLE [Tipoplatillo] 
 ADD CONSTRAINT [PK_Tipoplatillo]
	PRIMARY KEY CLUSTERED ([IdTipoPlatillo] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Bebida] ADD CONSTRAINT [FK_Bebida_Tipobebida]
	FOREIGN KEY ([TipobebidaID]) REFERENCES [Tipobebida] ([IdTipoBebida]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Comprainsumos] ADD CONSTRAINT [FK_Comprainsumos_Proveedor]
	FOREIGN KEY ([ProveedorID]) REFERENCES [Proveedor] ([ProveedorID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Comprainsumos] ADD CONSTRAINT [FK_Comprainsumos_RequerimientoDeInsumo]
	FOREIGN KEY ([RequerimientoDeInsumoID]) REFERENCES [RequerimientoDeInsumo] ([RequerimientoDeInsumoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ComprobanteDeVenta] ADD CONSTRAINT [FK_ComprobanteDeVenta_Cliente]
	FOREIGN KEY ([ClienteID]) REFERENCES [Cliente] ([ClienteID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ComprobanteDeVenta] ADD CONSTRAINT [FK_ComprobanteDeVenta_Ordenpedido]
	FOREIGN KEY ([OrdenpedidoID]) REFERENCES [Ordenpedido] ([OrdenpedidoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Detallepedido] ADD CONSTRAINT [FK_Detallepedido_Platillo]
	FOREIGN KEY ([PlatilloID]) REFERENCES [Platillo] ([PlatilloID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Detallepedido] ADD CONSTRAINT [FK_Detallepedido_Ordenpedido]
	FOREIGN KEY ([OrdenpedidoID]) REFERENCES [Ordenpedido] ([OrdenpedidoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Detallesreq] ADD CONSTRAINT [FK_Detallesreq_RequerimientoDeInsumo]
	FOREIGN KEY ([RequerimientoDeInsumoID]) REFERENCES [RequerimientoDeInsumo] ([RequerimientoDeInsumoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Detallesreq] ADD CONSTRAINT [FK_Detallesreq_Insumos]
	FOREIGN KEY ([InsumosID]) REFERENCES [Insumos] ([InsumosID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Ordenpedido] ADD CONSTRAINT [FK_Ordenpedido_Mesero]
	FOREIGN KEY ([MeseroID]) REFERENCES [Mesero] ([MeseroID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Platillo] ADD CONSTRAINT [FK_Platillo_Tipoplatillo]
	FOREIGN KEY ([TipoplatilloID]) REFERENCES [Tipoplatillo] ([IdTipoPlatillo]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [RequerimientoDeInsumo] ADD CONSTRAINT [FK_RequerimientoDeInsumo_Encargadoalmacen]
	FOREIGN KEY ([IDEncargado]) REFERENCES [Encargadoalmacen] ([EncargadoalmacenID]) ON DELETE No Action ON UPDATE No Action
GO


-- SCRIPT'S BEBIDA

-- LISTAR BEBIDAS
CREATE PROCEDURE [dbo].[spListarBebidas]
AS
BEGIN
    SELECT 
        BebidaID,
        Nombre_Bebida, 
        Precio,
        TamañoBebida,
        EstadoBebida,
		TipobebidaID
    FROM Bebida
    WHERE EstadoBebida = '1';
END;
GO

-- AGREGAR BEBIDAS

CREATE PROCEDURE [dbo].[spInsertarBebida]
	@BebidaID INT,
    @Nombre_Bebida VARCHAR(50),
    @Precio DECIMAL(10, 2),
    @TamañoBebida VARCHAR(20),
    @EstadoBebida BIT,
	@TipobebidaID INT
AS
BEGIN
    INSERT INTO Bebida (BebidaID ,Nombre_Bebida, Precio, TamañoBebida, EstadoBebida, TipobebidaID)
    VALUES (@BebidaID ,@Nombre_Bebida, @Precio, @TamañoBebida, @EstadoBebida, @TipobebidaID);
END;
GO

-- MODIFICAR BEBIDAS

CREATE PROCEDURE [dbo].[spEditarBebida]
	@BebidaID INT,
    @Nombre_Bebida VARCHAR(50),
    @Precio DECIMAL(10, 2),
    @TamañoBebida VARCHAR(20),
    @EstadoBebida BIT
AS
BEGIN
    UPDATE Bebida
    SET BebidaID = @BebidaID,
        Nombre_Bebida = @Nombre_Bebida,
        Precio = @Precio,
        TamañoBebida = @TamañoBebida,
        EstadoBebida = @EstadoBebida
    WHERE BebidaID = @BebidaID;
END;
GO

-- DESHABILITAR BEBIDAS

CREATE PROCEDURE [dbo].[spDeshabilitarBebida]
    @BebidaID INT
AS
BEGIN
    UPDATE Bebida
    SET 
        EstadoBebida = 0
    WHERE BebidaID = @BebidaID;
END;
GO


-- PROCEDIMIENTOS MANTENEDOR CLIENTE

--LISTAR CLIENTES
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spListarClientes]
AS
BEGIN
    SELECT
		ClienteID,
        Nombre_Cliente, 
        DNI, 
        Numero,
		Correo,
		Fecha,
		EstadoCliente
    FROM Cliente
	WHERE EstadoCliente = '1'
END;
GO

--AGREGAR CLIENTE
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spInsertarCliente]
    @ClienteID INT,
    @Nombre_Cliente VARCHAR(50),
    @DNI INT,
    @Numero INT,
	@Correo VARCHAR(50),
	@Fecha DATE,
	@EstadoCliente BIT
AS
BEGIN
    INSERT INTO Cliente (ClienteID, Nombre_Cliente, DNI, Numero, Correo, Fecha, EstadoCliente)
    VALUES (@ClienteID, @Nombre_Cliente, @DNI, @Numero, @Correo, @Fecha, @EstadoCliente);
END;
GO

-- SCRIPST CLIENTE
--MODIFICAR CLIENTE
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spEditarCliente]
	@ClienteID INT, 
    @Nombre_Cliente VARCHAR(50),
    @DNI INT,
    @Numero INT,
	@Correo VARCHAR(50),
	@Fecha DATE,
	@EstadoCliente BIT
AS
BEGIN
    UPDATE Cliente
    SET 
		ClienteID = @ClienteID,
        Nombre_Cliente = @Nombre_Cliente,
        DNI = @DNI,
		Numero = @Numero,
		Correo = @Correo,
		Fecha = @Fecha,
		EstadoCliente = @EstadoCliente
    WHERE ClienteID = @ClienteID;
END;
GO

--INHABILITAR CLIENTE

CREATE  PROCEDURE [dbo].[spDeshabilitarCliente] 
(@ClienteID int
)
AS
BEGIN 
	update  Cliente set 
	EstadoCliente = 0
	where ClienteID = @ClienteID
END
GO

--Procedimientos CompraInsumos

--listar
CREATE PROCEDURE [dbo].[spListarCompraReq]
AS
BEGIN
    SELECT 
        c.ComprainsumosID,
        c.Encargado,
        c.FechaCompra,
        c.MetodoPago,
        c.MontoTotal,
        c.RequerimientoDeInsumoID,
        r.FechaRegistro AS FechaRequerimiento, -- ejemplo
        c.ProveedorID,
        p.NombreProveedor,
        c.EstadoCompra
    FROM Comprainsumos c
    INNER JOIN Proveedor p ON c.ProveedorID = p.ProveedorID
    INNER JOIN RequerimientoDeInsumo r ON c.RequerimientoDeInsumoID = r.RequerimientoDeInsumoID;
END;
GO

--Registrar
CREATE PROCEDURE [dbo].[spRegistrarCompraReq]
	@ComprainsumosID INT,
    @Encargado VARCHAR(100),
    @FechaCompra DATETIME,
    @MetodoPago VARCHAR(50),
    @MontoTotal DECIMAL(10,2),
	@EstadoCompra BIT,
    @RequerimientoDeInsumoID INT,
    @ProveedorID INT
AS
BEGIN
    INSERT INTO Comprainsumos(ComprainsumosID ,Encargado, FechaCompra, MetodoPago, MontoTotal, EstadoCompra, RequerimientoDeInsumoID, ProveedorID)
    VALUES (@ComprainsumosID,@Encargado, @FechaCompra, @MetodoPago, @MontoTotal, @EstadoCompra, @RequerimientoDeInsumoID, @ProveedorID);

END;
GO

--Anular
CREATE PROCEDURE [dbo].[spAnularCompraReq]
    @ComprainsumosID INT
AS
BEGIN
    UPDATE Comprainsumos
    SET EstadoCompra = 0
    WHERE ComprainsumosID = @ComprainsumosID;
END;
GO


--Procedimientos Detalle REQUERIMIENTO

-- LISTAR DETALLE REQUERIMIENTO
CREATE PROCEDURE [dbo].[spListarDetalleReq] 
    @RequerimientoDeInsumoID INT
AS
BEGIN
    SELECT 
        d.DetallesreqID,
        d.RequerimientoDeInsumoID, 
        d.InsumosID,
        i.Nombre,
        d.Cantidad
    FROM Detallesreq d
    INNER JOIN Insumos i ON d.InsumosID = i.InsumosID
    WHERE d.RequerimientoDeInsumoID = @RequerimientoDeInsumoID; -- ← corregido aquí
END;
GO

-- INSERTAR DETALLE REQUERIMIENTO

CREATE PROCEDURE [dbo].[spInsertarDetalleReq]
    @RequerimientoDeInsumoID INT,
    @InsumosID INT,
    @Cantidad VARCHAR(50)
AS
BEGIN
    INSERT INTO Detallesreq (RequerimientoDeInsumoID, InsumosID, Cantidad)
    VALUES (@RequerimientoDeInsumoID, @InsumosID, @Cantidad);
END;
GO

--Procedimientos encargado del almacen 

-- LISTAR
CREATE PROCEDURE [dbo].[spListarEnAlmacen]
AS
BEGIN
    SELECT
		EncargadoalmacenID,
		DNI,
		Nombre,
		Numero,
		FechaRegistro,
		Estado
	FROM Encargadoalmacen
    WHERE Estado = 1
END
GO
-- INSERTAR

CREATE PROCEDURE [dbo].[spInsertarEnAlmacen]
	@EncargadoalmacenID INT,
    @DNI CHAR(8),
    @Nombre VARCHAR(100),
    @Numero VARCHAR(9),
    @FechaRegistro DATETIME,
    @Estado BIT
AS
BEGIN
    INSERT INTO Encargadoalmacen (EncargadoalmacenID ,DNI, Nombre, Numero, FechaRegistro, Estado)
    VALUES (@EncargadoalmacenID ,@DNI, @Nombre, @Numero, @FechaRegistro, @Estado)
END
GO

-- MODIFICAR
CREATE PROCEDURE [dbo].[spEditarEnAlmacen]
    @EncargadoalmacenID INT,
    @Nombre VARCHAR(50),
    @DNI INT,
    @Numero VARCHAR(9),
    @FechaIngreso DATETIME,
    @Estado BIT
AS
BEGIN
    UPDATE Encargadoalmacen
    SET EncargadoalmacenID = @EncargadoalmacenID,
        Nombre = @Nombre,
        DNI = @DNI,
        Numero = @Numero,
        FechaRegistro = @FechaIngreso,
        Estado = @Estado
    WHERE EncargadoalmacenID = @EncargadoalmacenID;
END;
GO

-- DESHABILITAR
CREATE PROCEDURE spDeshabilitarEnAlmacen
    @EncargadoalmacenID INT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE Encargadoalmacen
    SET Estado = 0
    WHERE EncargadoalmacenID = @EncargadoalmacenID;
END;


-- SCRIPST INSUMOS

--LISTAR INSUMOS

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spListarInsumos]
AS
BEGIN
    SELECT 
        InsumosID, 
        Nombre, 
        Cantidad,
		Estado
    FROM Insumos
	WHERE Estado = '1'
END;
GO

-- INSERTAR INSUMOS

CREATE PROCEDURE [dbo].[spInsertarInsumo]
	@InsumosID INT,
    @Nombre VARCHAR(100),
    @Cantidad VARCHAR(50),
    @Estado BIT
AS
BEGIN
    INSERT INTO Insumos (InsumosID ,Nombre, Cantidad, Estado)
    VALUES (@InsumosID, @Nombre, @Cantidad, @Estado);
END;
GO

------ MODIFICAR INSUMO
CREATE PROCEDURE [dbo].[spModificarInsumo]
	@InsumosID INT,
    @Nombre VARCHAR(100),
    @Cantidad VARCHAR(50),
    @Estado BIT
AS
BEGIN
    UPDATE Insumos
    SET InsumosID = @InsumosID,
		Nombre = @Nombre,
        Cantidad = @Cantidad,
        Estado = @Estado
    WHERE InsumosID = @InsumosID;
END;
Go

------ INHABILITAR INSUMOS

CREATE PROCEDURE [dbo].[spInhabilitarInsumo]
    (@InsumosID INT)
AS
BEGIN
    UPDATE Insumos set
    Estado = 0
    WHERE InsumosID = @InsumosID;
END;
GO

-- PROCEDIMIENTOS MANTENEDOR MESERO

--LISTAR MESERO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spListarMesero]
AS
BEGIN
    SELECT
		MeseroID,
        Nombre_Mesero, 
        DNI_Mesero, 
        Telefono,
		FechaIngreso,
		EstadoMesero
    FROM Mesero
	WHERE EstadoMesero = '1'
END;
GO

--AGREGAR MESERO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spInsertarMesero]	
	@MeseroID INT, 
    @Nombre_Mesero VARCHAR(100),
    @DNI_Mesero INT,
    @Telefono INT,
    @FechaIngreso DATE,
    @EstadoMesero BIT
AS
BEGIN
    INSERT INTO Mesero (MeseroID ,Nombre_Mesero, DNI_Mesero, Telefono, FechaIngreso, EstadoMesero)
    VALUES (@MeseroID ,@Nombre_Mesero, @DNI_Mesero, @Telefono, @FechaIngreso, @EstadoMesero);
END;
GO

--MODIFICAR MESERO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spEditarMesero]
	@MeseroID INT,
    @Nombre_Mesero VARCHAR(50),
    @DNI_Mesero INT,
    @Telefono INT,
	@FechaIngreso DATE,
	@EstadoMesero BIT
AS
BEGIN
    UPDATE Mesero
    SET MeseroID = @MeseroID,
        Nombre_Mesero = @Nombre_Mesero,
        DNI_Mesero = @DNI_Mesero,
		Telefono = @Telefono,
		FechaIngreso = @FechaIngreso,
		EstadoMesero = @EstadoMesero
    WHERE MeseroID = @MeseroID;
END;
GO

--INHABILITAR MESERO

CREATE  PROCEDURE [dbo].[spDeshabilitarMesero] 
(@MeseroID int
)
AS
BEGIN 
	update  Mesero set 
	EstadoMesero = 0
	where MeseroID = @MeseroID
END
GO

--- SCRIPT'S PLATILLO

-- LISTAR PLATILLO

CREATE PROCEDURE [dbo].[spListarPlatillos]
AS
BEGIN
	SELECT 
		PlatilloID, 
		NombrePlatillo, 
		Precio, 
		EstadoPlatillo,
		TipoPlatilloID
	FROM Platillo
    WHERE EstadoPlatillo = '1';
END;
GO

-- INSERTAR PLATILLO

CREATE PROCEDURE [dbo].[spInsertarPlatillo]
	@PlatilloID INT,
    @NombrePlatillo VARCHAR(100),
    @Precio DECIMAL(10, 2),
    @TipoPlatilloID INT,
    @EstadoPlatillo BIT
AS
BEGIN
    INSERT INTO Platillo (PlatilloID ,NombrePlatillo, Precio, TipoPlatilloID, EstadoPlatillo)
    VALUES (@PlatilloID ,@NombrePlatillo, @Precio, @TipoPlatilloID, @EstadoPlatillo);
END;
GO


-- MODIFICAR PLATILLO

CREATE PROCEDURE [dbo].[spEditarPlatillo]
	@PlatilloID INT, 
    @NombrePlatillo VARCHAR(100),
    @Precio DECIMAL(10, 2),
    @EstadoPlatillo BIT
AS
BEGIN
    UPDATE Platillo
    SET PlatilloID = @PlatilloID,
        NombrePlatillo = @NombrePlatillo,
        Precio = @Precio,
        EstadoPlatillo = @EstadoPlatillo
    WHERE PlatilloID = @PlatilloID;
END;
GO

-- DESHABILITAR PLATILLO

CREATE PROCEDURE [dbo].[spDeshabilitarPlatillo]
    @PlatilloID INT
AS
BEGIN
    UPDATE Platillo
    SET 
        EstadoPlatillo = 0 -- Cambiar a 0 para indicar que está descontinuado
    WHERE PlatilloID = @PlatilloID;
END;
GO


-- SCRIPTS PROVEEDOR   

-- LISTAR PROVEEDOR

CREATE PROCEDURE [dbo].[spListarProveedores]
AS
BEGIN
    SELECT
		ProveedorID,
        NombreProveedor,
        RUC,
        EmailProveedor,
        FechaProveedor,
        EstadoProveedor
    FROM Proveedor
    WHERE EstadoProveedor = '1';
END;
GO

-- INSERTAR PROVEEDOR

CREATE PROCEDURE [dbo].[spInsertarProveedor]
	@ProveedorID INT, 
    @NombreProveedor VARCHAR(255),
    @RUC VARCHAR(11), -- El RUC suele tener 11 dígitos para empresas en Perú
    @EmailProveedor VARCHAR(255),
    @FechaProveedor DATE,
    @EstadoProveedor BIT
AS
BEGIN
    INSERT INTO Proveedor (ProveedorID ,NombreProveedor, RUC, EmailProveedor, FechaProveedor, EstadoProveedor)
    VALUES (@ProveedorID ,@NombreProveedor, @RUC, @EmailProveedor, @FechaProveedor, @EstadoProveedor);
END;
GO

-- MODIFICAR PROVEEDOR

CREATE PROCEDURE [dbo].[spEditarProveedor]
	@ProveedorID INT,
    @NombreProveedor VARCHAR(255),
    @RUC VARCHAR(11),
    @EmailProveedor VARCHAR(255),
    @FechaProveedor DATE,
    @EstadoProveedor BIT
AS
BEGIN
    UPDATE Proveedor
    SET ProveedorID = @ProveedorID,
        NombreProveedor = @NombreProveedor,
        RUC = @RUC,
        EmailProveedor = @EmailProveedor,
        FechaProveedor = @FechaProveedor,
        EstadoProveedor = @EstadoProveedor
    WHERE ProveedorID = @ProveedorID;
END;
GO

-- DESHABILITAR PROVEEDOR

CREATE PROCEDURE [dbo].[spDeshabilitarProveedor]
(@ProveedorID INT
)
AS
BEGIN
    UPDATE Proveedor SET
    EstadoProveedor = 0
    WHERE ProveedorID = @ProveedorID;
END;
GO


-- SCRIPT'S TIPO DE BEBIDA

-- LISTAR TIPO DE BEBIDAS

CREATE PROCEDURE [dbo].[spListarTipoBebida]
AS
BEGIN
    SELECT 
        IdTipoBebida,
        NombreTipo,
        Estado
    FROM Tipobebida
    WHERE Estado = '1';
END;
GO

-- INSERTAR TIPO DE BEBIDA

CREATE PROCEDURE [dbo].[spInsertarTipoBebida]
	@IdTipoBebida INT,
    @NombreTipo NVARCHAR(100),
    @Estado BIT
AS
BEGIN
    INSERT INTO Tipobebida (IdTipoBebida ,NombreTipo, Estado)
    VALUES (@IdTipoBebida ,@NombreTipo, @Estado);
END;
GO

-- MODIFICAR TIPO DE BEBIDA

CREATE PROCEDURE [dbo].[spModificarTipoBebida]
	@IdTipoBebida INT, 
    @NombreTipo NVARCHAR(100),
    @Estado BIT
AS
BEGIN
    UPDATE Tipobebida
    SET IdTipoBebida = @IdTipoBebida,
		NombreTipo = @NombreTipo,
        Estado = @Estado
    WHERE IdTipoBebida = @IdTipoBebida;
END;
GO

-- INHABILITAR TIPO DE BEBIDA

CREATE PROCEDURE [dbo].[spInhabilitarTipoBebida]
    @IdTipoBebida INT
AS
BEGIN
    UPDATE Tipobebida
    SET Estado = 0
    WHERE IdTipoBebida = @IdTipoBebida;
END;
GO

-- SCRIPT'S TIPO DE PLATILLO

-- LISTAR TIPOS DE PLATILLO

CREATE PROCEDURE [dbo].[spListarTiposPlatillo]
AS
BEGIN
    SELECT 
        IdTipoPlatillo,
        NombreTipo, 
        Estado
    FROM Tipoplatillo
    WHERE Estado = 1; -- Solo listar los tipos de platillo que están activos
END;
GO

-- INSERTAR TIPOS DE PLATILLO

CREATE PROCEDURE [dbo].[spInsertarTipoPlatillo]
	@IdTipoPlatillo INT,
    @NombreTipo NVARCHAR(50),
    @Estado BIT
AS
BEGIN
    INSERT INTO Tipoplatillo (IdTipoPlatillo ,NombreTipo, Estado)
    VALUES (@IdTipoPlatillo ,@NombreTipo, @Estado);
END;
GO

-- EDITAR TIPOS DE PLATILLO

CREATE PROCEDURE [dbo].[spEditarTipoPlatillo]
    @IdTipoPlatillo INT,
    @NombreTipo NVARCHAR(50),
    @Estado BIT
AS
BEGIN
    UPDATE Tipoplatillo
    SET IdTipoPlatillo = @IdTipoPlatillo,
        NombreTipo = @NombreTipo,
        Estado = @Estado
    WHERE IdTipoPlatillo = @IdTipoPlatillo;
END;
GO

-- DESHABILITAR TIPO DE PLATILLO

CREATE PROCEDURE [dbo].[spDeshabilitarTipoPlatillo]
    @IdTipoPlatillo INT
AS
BEGIN
    UPDATE Tipoplatillo
    SET 
        Estado = 0 -- Cambiar a 0 para indicar que está inactivo
    WHERE IdTipoPlatillo = @IdTipoPlatillo;
END;
GO

-- CORE'S

-- SCRIPT'S CORE - ORDENPEDIDO

-- LISTAR ORDENPEDIDO

CREATE PROCEDURE [dbo].[spListarOrdenPedido]
AS
BEGIN
    SELECT 
        o.OrdenpedidoID,
        o.Fecha,
        o.NroMesa,
        o.Total,
        o.Estado,
		m.MeseroID,
        m.Nombre_Mesero
    FROM Ordenpedido o
    INNER JOIN Mesero m ON o.MeseroID = m.MeseroID
    WHERE o.Estado = '1'
    ORDER BY o.Fecha DESC;
END;
GO

-- REGISTRAR ORDENPEDIDO

CREATE PROCEDURE [dbo].[spAgregarOrdenPedido]
	@OrdenpedidoID INT,
    @Fecha DATETIME,
    @NroMesa INT,
    @Total DECIMAL(10,2),
    @Estado BIT,
    @MeseroID INT
AS
BEGIN
    INSERT INTO OrdenPedido (OrdenpedidoID ,Fecha, NroMesa, Total, Estado, MeseroID)
    VALUES (@OrdenpedidoID ,@Fecha, @NroMesa, @Total, @Estado, @MeseroID);
END;
GO

-- MODIFICAR ORDEN

CREATE PROCEDURE [dbo].[spModificarOrden]
    @OrdenpedidoID INT,
    @NroMesa INT,
    @Total DECIMAL(10, 2),
    @EstadoPedido BIT,
    @MeseroID INT
AS
BEGIN
    UPDATE OrdenPedido
    SET OrdenpedidoID = @OrdenpedidoID,
        NroMesa = @NroMesa,
        Total = @Total,
        Estado = @EstadoPedido,
        MeseroID = @MeseroID
    WHERE OrdenpedidoID = @OrdenpedidoID;
END;
GO


-- DESAHABILITAR VENTA

CREATE PROCEDURE [dbo].[spDeshabilitarOrdenPedido]
    @OrdenpedidoID INT
AS
BEGIN
    UPDATE Ordenpedido
    SET Estado = 0
    WHERE OrdenpedidoID = @OrdenpedidoID
END;
GO

-- DETALLE PEDIDO
-- LISTAR DETALLEPEDIDO

CREATE PROCEDURE [dbo].[spListarDetallePorPedido]
    @OrdenpedidoID INT
AS
BEGIN
    SELECT 
        dp.OrdenpedidoID,
        dp.DetallepedidoID,
        dp.PlatilloID,
        p.NombrePlatillo,
        dp.Cantidad,
        p.Precio AS Precio,
        dp.Subtotal
    FROM Detallepedido dp
    INNER JOIN Platillo p ON dp.PlatilloID = p.PlatilloID
    WHERE dp.OrdenpedidoID = @OrdenpedidoID
END
GO

GO

-- INSERTAR DETALLEPEDIDO - PARTE DE ORDENPEDIDO

CREATE PROCEDURE [dbo].[spInsertarDetallePedido]
	@OrdenpedidoID INT,
    @PlatilloID INT,
    @Cantidad INT,
    @Subtotal DECIMAL(10,2)
AS
BEGIN
    INSERT INTO Detallepedido (OrdenpedidoID, PlatilloID, Cantidad, Subtotal)
    VALUES (@OrdenpedidoID, @PlatilloID, @Cantidad, @Subtotal);
END;
GO

-- SCRIPT'S COMPROBANTE PAGO

GO

-- LISTAR COMPROBANTE

CREATE PROCEDURE [dbo].[spListarComprobantes]
AS
BEGIN
    SELECT 
        cp.ComprobanteDeVentaID,
		c.ClienteID,
        c.Nombre_Cliente AS NombreCliente,
        cp.OrdenpedidoID,
        cp.TipoComprobante,
        cp.FechaEmision,
        cp.MontoTotal,
        cp.EstadoComprobante
    FROM ComprobanteDeVenta cp
    INNER JOIN Cliente c ON cp.ClienteID = c.ClienteID
    ORDER BY cp.ComprobanteDeVentaID DESC;
END;
GO


-- INSERTAR COMPROBANTE

CREATE PROCEDURE [dbo].[spInsertarComprobante]
	@ComprobanteDeVentaID INT,  
    @ClienteID INT,
    @OrdenpedidoID INT,
    @TipoComprobante VARCHAR(50),
    @FechaEmision DATE,
    @MontoTotal DECIMAL(10,2),
    @EstadoComprobante BIT
AS
BEGIN
    INSERT INTO ComprobanteDeVenta (ComprobanteDeVentaID ,ClienteID, OrdenpedidoID, TipoComprobante, FechaEmision, MontoTotal, EstadoComprobante)
    VALUES (@ComprobanteDeVentaID ,@ClienteID, @OrdenpedidoID, @TipoComprobante, @FechaEmision, @MontoTotal, @EstadoComprobante);
END;
GO

-- ANULAR COMPROBANTE

CREATE PROCEDURE [dbo].[spAnularComprobante]
    @ComprobanteDeVentaID INT
AS
BEGIN
    UPDATE ComprobanteDeVenta
    SET 
        EstadoComprobante = 0 -- Cambiar a 0 para indicar que está anulado
    WHERE ComprobanteDeVentaID = @ComprobanteDeVentaID;
END;
GO

-- SCRIPT'S REQUERIMIENTO INSUMOS

-- LISTAR REQUERIMIENTO INSUMOS

CREATE PROCEDURE [dbo].[spListarRequerimientos]
AS
BEGIN
    SELECT 
        r.RequerimientoDeInsumoID,
        r.FechaRegistro,
        r.Estado,
		r.IDEncargado,
        e.Nombre AS NombreEncargado
    FROM RequerimientoDeInsumo r
    INNER JOIN Encargadoalmacen e ON r.IDEncargado = e.EncargadoalmacenID
	--where R.Estado = '1'
END;
GO

-- REGISTRAR REQUERIMIENTO INSUMOS
CREATE PROCEDURE [dbo].[spRegistrarRequerimiento]
	@RequerimientoDeInsumoID INT,
    @Estado BIT,
    @FechaRegistro DATE,
    @EncargadoalmacenID INT
AS
BEGIN
    INSERT INTO RequerimientoDeInsumo (RequerimientoDeInsumoID ,Estado, FechaRegistro, IDEncargado)
    VALUES (@RequerimientoDeInsumoID ,@Estado, @FechaRegistro, @EncargadoalmacenID)
END;
GO

-- ANULAR REQUERIMIENTO INSUMOS

CREATE PROCEDURE [dbo].[spAnularRequerimiento]
    @RequerimientoDeInsumoID INT
AS
BEGIN
    UPDATE RequerimientoDeInsumo
    SET Estado = 0
    WHERE RequerimientoDeInsumoID = @RequerimientoDeInsumoID;
END;
GO

-- ============================================================
-- CORRECIONES Y MEJORAS (ejecutar después del script original)
-- ============================================================

-- 1. NUEVO SP: Actualizar total de orden (reemplaza el SQL inline en C#)
GO
CREATE PROCEDURE [dbo].[spActualizarTotalOrden]
    @PedidoID INT,
    @Total DECIMAL(18,2)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE Ordenpedido SET Total = @Total WHERE OrdenpedidoID = @PedidoID;
END
GO

-- 2. CORREGIR spEditarBebida: faltaba @TipobebidaID en el UPDATE
GO
ALTER PROCEDURE [dbo].[spEditarBebida]
	@BebidaID INT,
    @Nombre_Bebida VARCHAR(50),
    @Precio DECIMAL(10, 2),
    @TamañoBebida VARCHAR(20),
    @EstadoBebida BIT,
    @TipobebidaID INT
AS
BEGIN
    UPDATE Bebida
    SET Nombre_Bebida = @Nombre_Bebida,
        Precio = @Precio,
        TamañoBebida = @TamañoBebida,
        EstadoBebida = @EstadoBebida,
        TipobebidaID = @TipobebidaID
    WHERE BebidaID = @BebidaID;
END
GO

-- 3. CORREGIR comparaciones BIT (EstadoBebida = '1' → EstadoBebida = 1)
GO
ALTER PROCEDURE [dbo].[spListarBebidas]
AS
BEGIN
    SELECT BebidaID, Nombre_Bebida, Precio, TamañoBebida, EstadoBebida, TipobebidaID
    FROM Bebida WHERE EstadoBebida = 1;
END
GO

GO
ALTER PROCEDURE [dbo].[spListarClientes]
AS
BEGIN
    SELECT ClienteID, Nombre_Cliente, DNI, Numero, Correo, Fecha, EstadoCliente
    FROM Cliente WHERE EstadoCliente = 1
END
GO

GO
ALTER PROCEDURE [dbo].[spListarInsumos]
AS
BEGIN
    SELECT InsumosID, Nombre, Cantidad, Estado
    FROM Insumos WHERE Estado = 1
END
GO

GO
ALTER PROCEDURE [dbo].[spListarMesero]
AS
BEGIN
    SELECT MeseroID, Nombre_Mesero, DNI_Mesero, Telefono, FechaIngreso, EstadoMesero
    FROM Mesero WHERE EstadoMesero = 1
END
GO

GO
ALTER PROCEDURE [dbo].[spListarPlatillos]
AS
BEGIN
    SELECT PlatilloID, NombrePlatillo, Precio, EstadoPlatillo, TipoPlatilloID
    FROM Platillo WHERE EstadoPlatillo = 1
END
GO

GO
ALTER PROCEDURE [dbo].[spListarProveedores]
AS
BEGIN
    SELECT ProveedorID, NombreProveedor, RUC, EmailProveedor, FechaProveedor, EstadoProveedor
    FROM Proveedor WHERE EstadoProveedor = 1
END
GO

GO
ALTER PROCEDURE [dbo].[spListarTipoBebida]
AS
BEGIN
    SELECT IdTipoBebida, NombreTipo, Estado
    FROM Tipobebida WHERE Estado = 1
END
GO

GO
ALTER PROCEDURE [dbo].[spListarTiposPlatillo]
AS
BEGIN
    SELECT IdTipoPlatillo, NombreTipo, Estado
    FROM Tipoplatillo WHERE Estado = 1
END
GO

-- 4. RECOMENDACIONES PARA CAMBIOS EN ESQUEMA DE BD (ejecutar manualmente si se requiere):
--    a. DNI en Cliente y Mesero a VARCHAR:
--       ALTER TABLE Cliente ALTER COLUMN DNI VARCHAR(8) NULL
--       ALTER TABLE Mesero ALTER COLUMN DNI_Mesero VARCHAR(8) NULL
--       ALTER TABLE Mesero ALTER COLUMN Telefono VARCHAR(15) NULL
--    b. Cantidad en Insumos y Detallesreq a DECIMAL:
--       ALTER TABLE Insumos ALTER COLUMN Cantidad DECIMAL(18,2) NULL
--       ALTER TABLE Detallesreq ALTER COLUMN Cantidad DECIMAL(18,2) NULL
--    c. Ordenpedido.Total a DECIMAL(18,2):
--       ALTER TABLE Ordenpedido ALTER COLUMN Total DECIMAL(18,2) NULL
--    d. Para usar IDENTITY en PKs (recomendado, recrear tablas):
--       Ejemplo: CREATE TABLE Cliente (ClienteID INT IDENTITY(1,1) PRIMARY KEY, ...)